services:
  claude-scheduler:
    image: ghcr.io/developerkubilay/claude-crone:latest
    container_name: claude_automation_scheduler
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=Europe/Istanbul
      - NODE_ENV=production
      - CHECK_INTERVAL_HOURS=24
    volumes:
      - ./services:/app/services
      - ./send_msg.py:/app/send_msg.py
      - ./config.json:/app/config.json
      - ./claude.json:/home/node/.claude/settings.json
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
